# 事件模块，这是 Nginx 的核心工作引擎配置区。即使你里面什么都不写，Nginx 也需要有这个大括号才
# 能启动。它默认会使用最高效的网络模型来处理并发连接（比如在 Ubuntu 上默认使用 epoll）
events {}

http {
    # 明确告诉 Nginx，我们的后台服务叫 web，跑在 8000 端口
    upstream backend_api {
        server web:8000;
    }
    server {
        listen 80;
        server_name 192.168.244.129; # 确保这里是你的虚拟机 IP
        location / {
            # 将请求转发给上面定义好的 backend_api
            proxy_pass http://backend_api;

            # 传递各种真实的头部信息给 FastAPI
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            # 这里修复了那个报错的变量名！
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}